# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeClient

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'


  target 'ReactNativeClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end